### ISSUE TITLE
update release.json automatically

### ISSUE THREAD

**Issue by zhmushan** [denolib/setup-deno#11]
Updating manually is stupid and needs to find a way to automate the process.

**Comment by axetroy** [comment]
I think it would be best if `deno.land` provided the version information

The second option is to build a proxy server to deploy to `heroku` or `now`

**Comment by axetroy** [comment]
The free plan of the third-party service (eg `heroku/now`) also has a limited number of requests

When the number of users is large, it is easy to exceed the limit

**Comment by axetroy** [comment]
I think it can be closed since #15 land
