### ISSUE TITLE
denolib/setup-deno@v1.1.0 deprecated

### ISSUE THREAD

**Issue by axetroy** [denolib/setup-deno#19]
v1.1.0 is deprecated

Please use `denolib/setup-deno@master` instead

```diff
steps:
  - uses: actions/checkout@master
- - uses: denolib/setup-deno@v1.1.0
+ - uses: denolib/setup-deno@master
    with:
      deno-version: 0.x
  - run: deno run https://deno.land/std/examples/welcome.ts
```

However, to ensure that the existing CI is not breaking

we will continue to maintain it to work properly until `2020/06/01`

**Comment by shian15810** [comment]
According to https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses:

> - Using the `master` branch of an action may be convenient, but if someone releases a new major version with a breaking change, your workflow could break.

I propose that we should follow what https://github.com/actions/checkout is doing, which is taking major version tag such as `v1` as a tag **only** and not a release, and every new release should be accompanied by the major release tag pointing to the same commit as the new release.

In this case of this repo, means that `v1` should point to the same commit as `v1.3.0`.

Any time that `v1.3.1` or `v1.4.0` should be published, `v1` should point to the commit of `v1.3.1` or `v1.4.0` too.

**Comment by prisis** [comment]
@axetroy i hope you going in the direction that @shian15810 proposed :), this would the best setup for the end user

**Comment by axetroy** [comment]
@shian15810 

I agree with your opinion

But it seems that `denolib/setup-deno@v1` is not correctly installed to `denolib/setup-deno@v1.3.0`

`denolib/setup-deno@v1` is 404 now

**Comment by axetroy** [comment]
`denolib/setup-deno@v2` is available now

We will follow the best style like `v1`/`v2` ...

notice: `denolib/setup-deno@v1` has been deprecated.
