### ISSUE TITLE
Permission denied with Deno v0.36.0

### ISSUE THREAD

**Issue by olaven** [denolib/setup-deno#33]
Thank you for this action! 

As the title says, my CI pipeline errored on `deno test` with the following, using 3.6:

`/home/runner/work/_temp/476f2026-a03c-44ac-be96-866004849968.sh: line 1: /opt/hostedtoolcache/deno/0.36.0/x64/deno: Permission denied
##[error]Process completed with exit code 126.`

See [this run](https://github.com/olaven/serialize-xml/runs/558064208) for an example. 

__note__: updating to 3.8 fixed the issue. 

Have a nice day! 😄

**Comment by zhmushan** [comment]
It should be caused by #31 
cc @axetroy

**Comment by axetroy** [comment]
@olaven Did you mean Deno v0.36.0 ?

**Comment by olaven** [comment]
@axetroy  Yes, my bad! [This release](https://github.com/denoland/deno/releases/tag/v0.36.0)

**Comment by axetroy** [comment]
Because the file of Deno v0.36.0 is not an executable file.

We only need to use the new file in ^v0.39.0 to solve this problem

**Comment by axetroy** [comment]
And this problem only exists in v0.36.0

v0.37.0 has fixed it

**Comment by olaven** [comment]
Thank you for looking into this! 😄
