### ISSUE TITLE
Lock file not being picked up

### ISSUE THREAD

**Issue by amsul** [denolib/setup-deno#37]
Is there some configuration that enables this?

Currently I'm getting this warning for every import:
```
Warning Implicitly using master branch https://deno.land/std/fs/mod.ts
```

**Comment by zhmushan** [comment]
@amsul Specify the version can resolve this warning.
e.g. `import {} from "https://deno.land/std@0.53.0/fs/mod.ts"`

And this isn't `setup-deno`'s issue.

**Comment by amsul** [comment]
I realize that you can specify the version in the URL. What I'm talking about is the lock file (https://deno.land/manual/linking_to_external_code/integrity_checking) as it is a stricter check than just a version.

**Comment by amsul** [comment]
I feel like this isn't an issue with setup-deno, but rather with one of the dependencies of my dependency that is not using a specific version. Probably safe to close this.
