### ISSUE TITLE
Deno version selection is broken

### ISSUE THREAD

**Issue by cj81499** [denolib/setup-deno#42]
The usage examples show both `v1.x`, `1.0.0`, and `0.42.0`.

Can I use `^1.0.0` to get anything up to `2.0.0`?

Is it preferable to include or leave off the "v"?

**Comment by zhmushan** [comment]
You can check the specific rules from [node-semver](https://github.com/npm/node-semver), maybe we need to inform in the readme.

**Comment by cj81499** [comment]
I just ran this (less than 5 minutes ago) in a private repository of mine.
Based on [caret ranges](https://github.com/npm/node-semver#caret-ranges-123-025-004), I'd expect it to grab `1.1.1`, but it grabs `1.0.0` instead.

![image](https://user-images.githubusercontent.com/9152032/85258919-39d95700-b436-11ea-8f68-adf3602eb9d7.png)

Is this a bug or am I doing something wrong?

**Comment by cj81499** [comment]
> You can check the specific rules from [node-semver](https://github.com/npm/node-semver), maybe we need to inform in the readme.

After fixing this bug, I think including this information in the readme would be very worthwhile.

**Comment by axetroy** [comment]
checkout to `denolib/setup-deno@v2`
