### ISSUE TITLE
##[error]Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by t8** [denolib/setup-deno#58]
We're finding this issue sporadically on one of our cron workflows. It doesn't happen often, but when it does, the CI fails. Here is a link to the specific error:

https://github.com/nestdotland/std/runs/933459310?check_suite_focus=true

Any ideas as to what the underlying issue may be?

Thanks in advance!

Tate

**Comment by axetroy** [comment]
@zhmushan I think there is a possibility:

When deno releases a new version, ry will initiate a PR

After merging the PR, wait for CI to complete and then publish to Github Release.

In this short period of time, a new version of `Release.md` has been added, but in fact, it has not been released in Github Release, so it may cause 404.

**Comment by zhmushan** [comment]
We may need a fallback mechanism, if the latest version does not exist, install the previous version

**Comment by zhmushan** [comment]
We can:
- Define a function to get the latest version from GitHub Release
- Remove versions larger than LTS in `queryLatestMatch()`

**Comment by t8** [comment]
That makes a lot of sense. Thanks for such a quick response! Looking forward to the solution.

**Comment by MikaelPorttila** [comment]
This is happening again, both on @master and @v2

**Comment by axetroy** [comment]
> This is happening again, both on @master and @v2

> In this short period of time, a new version has been added to Release.md, but in fact, it has not been released in Github Release, so it may cause 404.

as I say before. Deno v1.5.0 just release a minute before.

**Comment by axetroy** [comment]
close this since #74 has been merged
