### ISSUE TITLE
Use original binary name for nightly builds?

### ISSUE THREAD

**Issue by maximousblk** [denolib/setup-deno#59]
I know I [justified](https://github.com/denolib/setup-deno/issues/48#issuecomment-659146094) the use of name `deno-nightly` for the binary, but I think it would be better to use `deno` for the name so that it is easier to use with matrix configurations. And for the manual installers, we can rename the binary in the script itself.

Now the question is, should I do that? because this action is the major way of using these builds and this update will break all the workflows that are using the nightly builds from this action.

**Comment by maximousblk** [comment]
So I have decided to go with this change. The action itself won't break, just wanted to notify so you could update the docs.

also might wanna follow this: https://github.com/denoland/deno/issues/6974

**Comment by axetroy** [comment]
> I think it would be better to use deno for the name so that it is easier to use with matrix configurations

We can use `if: matrix.deno ==='nightly'` to distinguish with stable version

Regarding whether to use deno or `deno-nightly`

I prefer `deno`, but disruptive updates are really annoying.

Of course, we can make a compatible, copy `deno-nightly` to `deno` and two executable files.

----  ----

**Comment by maximousblk** [comment]
> BREAKING CHANGE updates are really annoying.


Yes that is true but I don't think many people are using it for the time being.

We use it at nest.land which won't be a problem because I'm a maintainer there. Don't know about othr projects.

But it's an easy fix and it won't affect the module consumers.

**Comment by maximousblk** [comment]
take a look at https://github.com/search?q=deno-nightly&type=Code
only nest.land and my personal projects are using it.

**Comment by axetroy** [comment]
@maximousblk all right. LGTM.

@zhmushan How about this? We just need to rename `deno-nightly` file to `deno`.

**Comment by maximousblk** [comment]
do note that only the binary name is changing, not the zip file names.

**Comment by axetroy** [comment]
> do note that only the binary name is changing, not the zip file names.
> [maximousblk/deno_nightly#1](https://github.com/maximousblk/deno_nightly/pull/1)

If this is merged, this repo does not require any changes.

It will take effect after the nightly version is released the next day, because there is no renaming process, but directly unzip.

I only need to update the README at that time.

Good! 👍

**Comment by axetroy** [comment]
@maximousblk Could you trigger CI to release today's nightly build?

Because I am preparing to merge #60, But because there is no nightly build exist, CI is always red now.

**Comment by maximousblk** [comment]
I have triggered the build process. I takes around 30 minutes on windows so you need to wait until then.

**Comment by zhmushan** [comment]
> We just need to rename deno-nightly file to deno.
I agree

**Comment by maximousblk** [comment]
@axetroy build completed: https://github.com/maximousblk/deno_nightly/releases/tag/2020.08.07

**Comment by axetroy** [comment]
@maximousblk  since `v2.2.0` has been released.

now it should work with `denolib/setup-deno@v2`
