### ISSUE TITLE
Times Out for MacOS-Latest

### ISSUE THREAD

**Issue by ebebbington** [denolib/setup-deno#65]
Example: https://github.com/drashland/deno-drash/runs/1038925045
The workflow the example above uses: https://github.com/drashland/deno-drash/blob/master/.github/workflows/master.yml

Using for macos-latest seems to hang forever, then timeout, but works for windows and ubuntu, and in the above workflow, the only difference for the environments is the OS

```
Run denolib/setup-deno@v2
connect ETIMEDOUT 52.216.170.227:443
Waiting 18 seconds before trying again
connect ETIMEDOUT 52.216.93.243:443
Waiting 13 seconds before trying again
##[error]connect ETIMEDOUT 52.216.225.216:443
```

**Comment by axetroy** [comment]
eh. interesting. But I don't think it is a BUG.

It seems the network trouble in Github Action Container.

**Comment by ebebbington** [comment]
Yeah very odd - i've just re-ran the build (been re-running it a few times to keep an eye on it) and it seems to be working again

Good it isn't a bug :D
