### ISSUE TITLE
"The `add-path` command is deprecated and will be disabled soon." is this module raising the waring? 

### ISSUE THREAD

**Issue by garronej** [denolib/setup-deno#69]
Hi,
Not 100% sure but I think this warning comme from this action.

![image](https://user-images.githubusercontent.com/6702424/96929808-0e857800-14bb-11eb-8c50-44340fbdfa39.png)

[ref](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)

I see 'set-env' popping up in the dist index.

Best regards

**Comment by axetroy** [comment]
I think this issue should be resolve after #68 merged

**Comment by garronej** [comment]
Great thx
