### ISSUE TITLE
Security error when using Action

### ISSUE THREAD

**Issue by vegerot** [denolib/setup-deno#78]
Please see https://github.com/vegerot/AdventOfCode/pull/1/checks?check_run_id=1618898179

It looks like [addPath](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) has been deprecated and removed.

I would appreciate assistance on how I should replace the [current usage](https://github.com/denolib/setup-deno/blob/master/src/installer.ts#L78-L80).

**Comment by axetroy** [comment]
It seems that I did not receive such a warning.

Prior to this, we have performed a dependency upgrade according to Github’s prompts. #68 

This warning shouldn't reappear

**Comment by vegerot** [comment]
Thank you!
