### ISSUE TITLE
Got a wrong version from Deno release

### ISSUE THREAD

**Issue by LitoMore** [denolib/setup-deno#81]
https://github.com/denolib/setup-deno/runs/1892711261?check_suite_focus=true

The expected version should be `v1.7.2`.

Although [denoland/deno](https://github.com/denoland/deno/releases) has released `v1.7.3`, their latest release is still `v1.7.2`.

**Comment by LitoMore** [comment]
The `v1.7.4` is out. The online failing issue is solved. But we still need to fix the bug in `setup-deno`.

**Comment by zhmushan** [comment]
@LitoMore 1.7.3 is not included in the version list. see https://github.com/denoland/deno_website2/blob/main/versions.json

**Comment by LitoMore** [comment]
@zhmushan It was. Check this https://github.com/denoland/deno_website2/commit/51c5c65d0d1e93fde40d3ade08ceea7c2f4f00ec#diff-2b39d33506bc7a34cef4b9ebf4cf8b1e3a5532f2131ceb37011b94261cec5f8c

**Comment by zhmushan** [comment]
@LitoMore We will only refer to the latest version list. This is the conclusion obtained in the [previous issue](https://github.com/denolib/setup-deno/issues/47#issuecomment-728946382). I will make it clear in the document.
